# Generated by Django 5.0.4 on 2024-04-10 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='place_id',
            new_name='place',
        ),
    ]
