# Generated by Django 5.0.4 on 2024-04-10 18:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_place_id_blog_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='publish_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
