# Generated by Django 5.0.4 on 2024-04-11 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blog_publish_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='place_address',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='place_country',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='place_name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='place',
            name='place_state',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
