# Generated by Django 5.0.4 on 2024-04-22 17:03

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_blog_date_when'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='gallery_image',
            field=models.FileField(blank=True, null=True, upload_to=blog.models.blog_gallery_image_path),
        ),
        migrations.AlterField(
            model_name='blog',
            name='content_file',
            field=models.FileField(upload_to=blog.models.blog_content_file_path),
        ),
    ]
