# Generated by Django 5.0.4 on 2024-04-22 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_blog_gallery_image_alter_blog_content_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='blog',
            name='gallery_image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
