# Generated by Django 4.2.11 on 2024-05-28 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_blog_content_file_alter_blog_gallery_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='post_type',
            field=models.ManyToManyField(to='blog.posttype'),
        ),
    ]
